service: serverless-aws-nodejs

custom:
  tableName: 'reports-${self:provider.stage}'
  bucket: s3-upload-pdfreports

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["ReportTable", "Arn" ] }
  environment:
    REPORT_TABLE: ${self:custom.tableName}
    BUCKET_NAME: ${self:custom.bucket}

functions:
  create:
    handler: report/create.create
    events:
      - http:
          path: report
          method: post

  edit:
    handler: report/edit.edit
    events:
      - http:
          path: report/{id}
          method: put

  get:
    handler: report/get.get
    events:
      - http:
          path: report/{id}
          method: get

  all:
    handler: report/all.all
    events:
      - http:
          path: reports
          method: get

  csv:
    handler: report/csv.csv
    events:
      - http:
          path: csv
          method: get

  pdf_report:
    handler: report/pdf_report.pdf_report
    events:
      - httpApi:
          path: /api/pdf_report
          method: get

  delete:
    handler: report/delete.delete
    events:
      - http:
          path: report/{id}
          method: delete

resources:
  Resources:
    ReportTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
plugins:
  - serverless-plugin-common-excludes
